# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = []
description = "OpenTelemetry README Example in TypeScript"
language = "javascript"
manifest_version = 2
name = "readme-demo-ts"

[local_server]
[local_server.backends]
[local_server.backends.otlp-collector]
url = "http://localhost:4318/"

[scripts]
build = "npm run build"
